services:
  letta-mcp:
    image: ghcr.io/oculairmedia/letta-mcp-server:latest
    ports:
      - "${PORT:-3001}:3001"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LETTA_BASE_URL=${LETTA_BASE_URL}
      - LETTA_PASSWORD=${LETTA_PASSWORD}
      - NODE_ENV=${NODE_ENV:-production}