name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          LETTA_BASE_URL: ${{ secrets.LETTA_BASE_URL || 'https://test.letta.com/v1' }}
          LETTA_PASSWORD: ${{ secrets.LETTA_PASSWORD || 'test-password' }}

      - name: Check code quality
        run: |
          npm run lint
          npm run format:check

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Bump version (manual trigger only)
        if: github.event_name == 'workflow_dispatch'
        run: |
          npm version ${{ github.event.inputs.version }} -m "chore: release %s [skip ci]"
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
          git push origin master --follow-tags
        id: new-version

      - name: Build package
        run: npm pack

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release (manual trigger only)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.new-version.outputs.version || steps.package-version.outputs.version }}
          release_name: Release v${{ steps.new-version.outputs.version || steps.package-version.outputs.version }}
          body: |
            ## Changes in this release
            
            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md) for details.
            
            ## Installation
            
            ```bash
            npm install -g letta-mcp-server@${{ steps.new-version.outputs.version || steps.package-version.outputs.version }}
            ```
          draft: false
          prerelease: false

      - name: Notify success
        if: success()
        run: |
          echo "✅ Successfully published letta-mcp-server@${{ steps.new-version.outputs.version || steps.package-version.outputs.version }} to npm!"
          echo "View at: https://www.npmjs.com/package/letta-mcp-server"

      - name: Notify failure
        if: failure()
        run: |
          echo "❌ Failed to publish package to npm"
          echo "Check the logs above for error details"